fix: target actor unique ID serialization
pmmp/BedrockProtocol pull request #271
Opened 2024-09-16 05:51 UTC by nicholass003

Fixes https://github.com/pmmp/BedrockProtocol/issues/268

2024-09-16 16:36 UTC, nicholass003 commented
Tested and working fine

https://github.com/user-attachments/assets/2c406434-63cf-4134-ab62-2924321fec4e

2024-09-16 17:24 UTC, IvanCraft623 requested changes
@TwistedAsylumMC or @dries-c Can you confirm this?

2024-09-16 17:24 UTC, IvanCraft623 commented on src/types/camera/CameraTargetInstruction.php
> +		private int $targetActorUniqueId //This is a little-endian long, NOT a var-long. (WTF Mojang)
No need to change the property name

2024-09-16 17:24 UTC, IvanCraft623 commented on src/types/camera/CameraTargetInstruction.php
> +		private int $targetActorUniqueId //This is a little-endian long, NOT a var-long. (WTF Mojang)
This command belongs to de/serealization, not the constructor

2024-09-18 11:56 UTC, TwistedAsylumMC submitted a review, later dismissed

2024-09-18 16:00 UTC, dries-c approved these changes

2024-09-18 20:48 UTC, IvanCraft623 approved these changes

2024-09-18 20:53 UTC, dries-c approved these changes

2024-09-18 20:58 UTC, merged